2024-08-26 21:33:12,144 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Python\Practice\modul12\tests_12_4.py", line 23, in test_run
    runner1 = rt_with_exceptions.Runner(["Oleg", 228])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Practice\modul12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-08-26 21:33:12,145 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Python\Practice\modul12\tests_12_4.py", line 12, in test_walk
    runner1 = rt_with_exceptions.Runner("Oleg", -5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Practice\modul12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
